server connected to mongoDB, tested with Postman
borisolah/Site-Creator pull request #20
Opened 2023-03-11 11:57 UTC by borisolah

Successfully set up the MongoDB Atlas and connected it to the Express server, tested login and register functions via  Postman, hashed and salted the passwords using bycript and handled a few error messages such as password too short, invalid E-mail, or user already registered.

2023-03-17 09:09 UTC, csillagkrisztian requested changes
Super clean PR! Looks professional! Although I have a few questions and ideally you would add a comment before big functions to explain in short what they are doing and why!

2023-03-17 09:09 UTC, csillagkrisztian commented on server/controllers/authController.js
> +  return jwt.sign({ id }, "string secret comes here", {
What does that "string secret comes here" mean? If you are supposed to be generating a secret, is that hard to do?

2023-03-17 09:09 UTC, csillagkrisztian commented on server/controllers/authController.js
> +    expiresIn: maxAge,
Also, what is maxAge? JWT tokens should expire in a reasonable amount of time, let's say a week for security's sake, so people don't forget their credentials.

2023-03-17 09:09 UTC, csillagkrisztian commented on server/controllers/authController.js
> +  res.render("signup");
are you rendering stuff on the server?

2023-03-17 09:09 UTC, csillagkrisztian commented on server/controllers/authController.js
> +    res.cookie("jwt", token, { httpOnly: true, maxAge: maxAge * 1000 });
Why is it maxAge *1000?

2023-03-17 09:09 UTC, csillagkrisztian commented on server/server.js
> +// view engine
What do you mean by engine?

2023-03-17 09:54 UTC, borisolah commented on server/controllers/authController.js
> +    res.cookie("jwt", token, { httpOnly: true, maxAge: maxAge * 1000 });
So this part of the code required miliseconds, and not seconds, so I just multiplied the whole 3 days by 1000 and that should have given me 3 days in miliseconds.

2023-03-17 09:56 UTC, borisolah commented on server/controllers/authController.js
> +  return jwt.sign({ id }, "string secret comes here", {
This and the mongoDB Atlas usernape/password part are a bit difficult to implement. I'm going to have to use specific keys to gain access to the databse from the server, and I did not want to upload those tot he github hence had a string telling me where to put it in the future.

I will need to do excessive research on how to do this properly in a more professional manner.

2023-03-17 09:59 UTC, borisolah commented on server/controllers/authController.js
> +  res.render("signup");
Thank you for pointing this out, somwhow I've missed it. I wanted to test something out with singing up without a React client and forgot to change it back after. 

Fixed it up just now.

2023-03-17 10:14 UTC, csillagkrisztian commented on server/controllers/authController.js
> +  return jwt.sign({ id }, "string secret comes here", {
To use secret strings you should use environment variables
They are .env files, that should not be pushed to the repo, but can be local on your machine.

2023-03-17 10:18 UTC, csillagkrisztian commented on server/controllers/authController.js
> +    expiresIn: maxAge,
sure, but then maxAge refers to the age of the token not the user, I think this is confusing, so I would prefer that you name it, expirationDate or Time

Also if you want to make it even more clear, just do it this way
const dayInSeconds = 86400;
const expiryDate = 3 * dayInSeconds;
This way it's clear what the day is and what the rest is as well.

2023-03-17 10:21 UTC, borisolah commented on server/controllers/authController.js
> +    expiresIn: maxAge,
That is true. I will fix it up and make a new commit in a minute.

2023-03-17 11:17 UTC, csillagkrisztian requested changes

2023-03-17 11:17 UTC, csillagkrisztian commented on server/controllers/authController.js
> +  return jwt.sign({ id }, "string secret comes here", {
I have to comment again! Either decide to use shorthands or never use them ever. Usually the never use them ever is the winner. It makes the code a bit large but the readabolity is massive

2023-03-17 13:24 UTC, borisolah commented on server/controllers/authController.js
> +  return jwt.sign({ id }, "string secret comes here", {
All right, I'll keep it with not using shorthands then.

2023-03-18 17:49 UTC, csillagkrisztian approved these changes

2023-03-18 17:49 UTC, merged