Cleaned up some code, made some changes for functionality, added user roles.
borisolah/Site-Creator pull request #21
Opened 2023-04-05 14:45 UTC by borisolah

Added user roles such as Permium, and Trial to set up the website. Made sure CORS works properly, double checked security.

2023-04-11 19:04 UTC, csillagkrisztian commented on client/src/api/axios.js
> +export default axios.create({
High level magic right here <3

2023-04-11 19:47 UTC, csillagkrisztian requested changes
Plenty of questions, but overall nice on the implementation. Sadly I can't functionally test whether any of this works, which is a bummer, since I can't be sure that it works together as neatly as you implemented it. For the next PR I would expect less files changed, so I can read through the code more easily, otherwise it's waaay too much work for me to understand what changed. 

Also the branch names are not ideal. Once you create a branch, don't name it simply "server", instead I would focus on more of a story based approach

SC-0001 for the first story branch would be perfect, and on the project log, you can also name the tasks accordingly, connecting them in the process, making it easier to track which branch is responsible for which story.


Also you mentioned some weird things have changed, so let me know when you change them back!

2023-04-11 19:47 UTC, csillagkrisztian commented on client/src/pages/Login/Login.js
> +      <div className="email error">some error</div>
some error? Is this a placeholder for future errors, or is it an actual error text already?

2023-04-11 19:47 UTC, csillagkrisztian commented on server/package.json
>    "scripts": {
Script is incorrect, I can't test server with command

2023-04-11 19:47 UTC, csillagkrisztian commented on server/package.json
>    "scripts": {
Also upon running npx nodemon server.js I get Mongo errors, is this supposed to happen? If so, change it, it should instead write out a console log, like The dabase is not implemented yet, etc.

2023-04-11 19:47 UTC, csillagkrisztian commented on server/middleware/verifyRoles.js
> +    console.log(req.roles);
remove console.logs

2023-04-11 19:47 UTC, csillagkrisztian commented on client/src/api/axios.js
> +export default axios.create({
get to it!

2023-04-11 19:47 UTC, csillagkrisztian commented on client/src/pages/Login/Login.js
> +    // Add code to send login data to server
This is a good solution, maybe console log this too! This will send it to the db some day.

2023-04-11 19:47 UTC, csillagkrisztian commented on client/src/pages/Signup/Signup.js
> +      const response = await fetch("http://localhost:3500/signup", {
Maybe your port on server isn't setup correctly?

2023-04-11 19:47 UTC, csillagkrisztian commented on server/config/allowedOrigins.js
> +  "https://www.yoursite.com",
What? 🗡️

2023-04-11 19:47 UTC, csillagkrisztian commented on server/controllers/logoutController.js
> +    res.clearCookie("jwt", { httpOnly: true, sameSite: "None", secure: true });
+1

2023-04-11 19:47 UTC, csillagkrisztian commented on server/logs/reqLog.txt
> +20230402	11:32:09	6a6ed9d4-cd13-4d35-bc54-4942f99cb235	GET	undefined	/
I might format this line slightly better to make it more readable

2023-04-25 08:07 UTC, borisolah commented on server/package.json
>    "scripts": {
.env file should have the mongodb atlas string key that authenticates your application. I'll just build a database myself for good practice though. Using the Atlas is easy.

2023-04-25 08:14 UTC, borisolah commented on server/model/User.js
> +const userSchema = new Schema({
config/dbConn.js we should be connected to mongoDB Atlas

2023-04-25 08:14 UTC, borisolah commented on client/src/pages/Signup/Signup.js
> +      const response = await fetch("http://localhost:3500/signup", {
The client side is problematic it seems. I'll review it today and give it a proper fix.

2023-04-25 08:28 UTC, borisolah commented on server/routes/api/users.js
> +    verifyRoles(ROLES_LIST.Premium, ROLES_LIST.User, ROLES_LIST.Trial),
I see, definitely a better approach, noted.

2023-04-25 08:35 UTC, borisolah commented on server/routes/root.js
> +router.get("^/$|/index(.html)?", (req, res) => {
Hahaha fancy stuff for it can be / alone /index or /index.html all three will lead to the same route.

2023-05-02 13:09 UTC, csillagkrisztian approved these changes
Nice one! Get to creating more soon!

2023-05-02 13:09 UTC, merged