Server
borisolah/Site-Creator pull request #22
Opened 2023-06-02 15:05 UTC by borisolah

Protected certain routes from entry. Only premium members can enter certain areas of teh website. Also register and login functions work fine.

2023-06-20 19:20 UTC, csillagkrisztian requested changes
Great job, relatively few comments compared to the size of the PR, try to keep them a bit smaller scope next time!

2023-06-20 19:20 UTC, csillagkrisztian commented on server/logs/errLog.txt
> +20230513	13:07:40	225201e7-8a15-44b0-928e-ccd919f07cfa	Error: Not allowed by CORS
You shouldn't store logs on your repository, because every time you push, it just keeps growing. I would use a database collection called logs and just save it there

2023-06-20 19:20 UTC, csillagkrisztian commented on client/src/pagecomponents/logincomponents/PersistLogin.js
> +    console.log(`isLoading: ${isLoading}`);
What's the purpose of these console.logs

2023-06-20 19:20 UTC, csillagkrisztian commented on client/src/pagecomponents/hooks/useRegisterHook.js
> +      const response = await axios.post("http://localhost:3500/register", {
`await axios.post(`${baseURL}/register`,...)`
This should be an environment variable. If you push this to production, it won't work.

2023-06-20 19:20 UTC, csillagkrisztian commented on client/src/pagecomponents/authcontrollers/axios.js
> +  baseURL: BASE_URL,
Here you have a baseURL lol, just export it and use it!

2023-06-20 19:20 UTC, csillagkrisztian commented on client/src/pagecomponents/authcontrollers/authProvider.js
> +import { createContext, useState } from "react";
React Context? This is an alternative to Redux, I would decide on either using one or the other for less confusion.

2023-06-20 19:20 UTC, csillagkrisztian commented on client/src/pagecomponents/MapComponent.js
> +      <Text>IDEMO</Text>
alllright? IDEMO, isn't a clear plan

2023-06-21 18:45 UTC, borisolah commented on server/logs/errLog.txt
> +20230513	13:07:40	225201e7-8a15-44b0-928e-ccd919f07cfa	Error: Not allowed by CORS
Absolutely true, nice catch! I'll be making a separate PR for this. You can find the issue [here](https://github.com/borisolah/Site-Creator/issues/24).

2023-06-21 18:48 UTC, borisolah commented on client/src/pagecomponents/logincomponents/PersistLogin.js
> +    console.log(`isLoading: ${isLoading}`);
Nothing. You are right, the PR is a bit too big, so it seems I've managed to miss some console logs used for debugging....
I'll remove them now.

2023-06-21 18:55 UTC, borisolah commented on client/src/pagecomponents/hooks/useRegisterHook.js
> +      const response = await axios.post("http://localhost:3500/register", {
Thanks for pointing this out
Created another project. I'll clear these up in a smaller PR. [Here](https://github.com/borisolah/Site-Creator/issues/25) you can find the link to the said project.

2023-06-21 19:15 UTC, borisolah commented on client/src/pagecomponents/authcontrollers/axios.js
> +  baseURL: BASE_URL,
Mhmm, I will include this to the .env PR, is that a good way to approach this? Since they are similar, could fix both issues at once.

2023-06-21 19:19 UTC, borisolah commented on client/src/pagecomponents/authcontrollers/authProvider.js
> +import { createContext, useState } from "react";
For educational purposes only. I was following a tutorial that goes through different parts of login. Currently we use React Context, and will switch to Redux in the next chapter. That will be a few pull requests away though, since I'm decreasing the size of the PRs .

It was a fun learning experience though!

2023-06-21 19:19 UTC, borisolah commented on client/src/pagecomponents/MapComponent.js
> +      <Text>IDEMO</Text>
Jeez. Fixed!

2023-06-29 20:07 UTC, csillagkrisztian approved these changes

2023-06-29 20:07 UTC, merged