Login finished, looks stable and un-hackable!
borisolah/Site-Creator pull request #29
Opened 2023-06-30 07:26 UTC by borisolah

In this PR I have completed the first milestone with a hand made register and login functionality relying on JWT, bcrypt, and refresh / auth tokens.
The end result : when you log in, you stay logged in for a few days, even after closing the browser or the whole react application, unless you log out of course. While this may sound simple enough, building it the first time around taught me a whole lot about security in the web developers world.
It is ready for testing. And for security purposes, I will include Csillag Krisztián as well as Oláh Attila, two incredible programmers, to review my code and make sure its solid as a rock.

2023-06-30 08:07 UTC, csillagkrisztian requested changes
Nice PR! This time I am also bappy about the pr's size and just a few comments left here and there.

2023-06-30 08:07 UTC, csillagkrisztian commented on server/logs/reqLog.txt
> +20230627	16:09:08	a1e805c5-8888-4c2a-a19b-3ec84505b1f1	GET	http://localhost:3000	/logout
This log seems to continue growing. It should be a database's resposibility to store the logs rather than a file that is not ignored by git

2023-06-30 08:07 UTC, csillagkrisztian commented on client/src/pagecomponents/PersistLogin.js
> +
Can you explain in short why there are two expiration mechanisms one on the server and one on the client?

2023-06-30 10:33 UTC, borisolah commented on client/src/index.js
> +disableReactDevTools();
Yeah, I wanted to sneak it in and just manually disable it whenever I want to use it, but actually this is the correct approach. Especially when working in a team environment, we should follow best practices. 
Thanks for pointing it out. Fixed.

2023-06-30 10:39 UTC, borisolah commented on client/src/pagecomponents/Navbar.js
> +      zIndex="1000"
Done and done!

2023-06-30 10:52 UTC, borisolah commented on client/src/pagecomponents/PersistLogin.js
> +
Actually. 
I have had a long debugging session and tried to kick the user out on the client side after a while, it left a few lines of unnecessary code...

Fixed it.

2023-06-30 10:54 UTC, borisolah commented on client/src/pagecomponents/PersistLogin.js
> +
I'm actually unsure. Focusing on security and functionality, it seems I've missed quite a few things here.

2023-06-30 11:06 UTC, borisolah commented on server/logs/reqLog.txt
> +20230627	16:09:08	a1e805c5-8888-4c2a-a19b-3ec84505b1f1	GET	http://localhost:3000	/logout
I see!

This is exactly why we need PR's... Even though I was working on the project I did not notice the log files growing, so when one pushes it to github they can just review the changes and spot anything like this > that should have been fixed but keeps growing, or isnt in place properly.

2023-07-01 21:24 UTC, csillagkrisztian commented on client/src/pagecomponents/Navbar.js
>    const navigate = useNavigate();
But then if you are forcing the destructure then why skip navigate? I believe you should NOT destructure them unless they return multiple values

2023-07-01 21:28 UTC, borisolah commented on client/src/pagecomponents/Navbar.js
>    const navigate = useNavigate();
You are right, if there are multiple values there is sense in deconstructing them, but with only one it does seem completely unnecessary.

I will rewrite the code and not deconstruct unless we have multiple values.

2023-07-01 22:39 UTC, csillagkrisztian approved these changes

2023-07-01 22:40 UTC, merged